apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
  - name: web-server
    image: nginx:alpine
    ports:
    - containerPort: 80
  - name: log-generator  
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo 'Log from sidecar container'; sleep 5; done"]
