apiVersion: v1
kind: Pod
metadata:
  labels:
    run: multi-pod
  name: multi-pod
spec:
  containers:
  - image: nginx
    name: multi-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
